---
# Services to enable
_{{ cookiecutter.role_name }}_services_enable:
  all: []
  CentOS_7: []
  RedHat_7: []
  CentOS_8: []
  RedHat_8: []
  Fedora_35: []
  Debian_10: []
  Ubuntu_18: []
  Ubuntu_20: []
