---
# install archive to /usr/local/bin
{% raw %}
- name: check if {{ item.dest }} is already installed
  command: {{ item.dest }} --version
  changed_when: false
  ignore_errors: yes
  register: version_output

- name: install {{ item.name }} if not already installed
  block:
    - name: unpacking tools preset
      package:
        name:
          - tar
          - gzip
          - unzip
        state: present
      become: true

    - name: create temporary file
      tempfile:
        state: file
        suffix: temp
      register: tmp_archive

    - name: download {{ item.name }}
      get_url:
        url: "{{ item.url }}"
        dest: "{{ tmp_archive }}"
        checksum: "sha256:{{ item.sha256 }}"

    - name: unarchive {{ item.name }}
      unarchive:
        src: "{{ tmp_archive }}"
        dest: "{{ item.dir }}"
        extra_opts:
          - --strip=1
        remote_src: yes
      become: yes

    - name: delete temp file
      file:
        path: "{{ tmp_archive }}"
        state: absent
  when: "( version_output is failed ) or ( {{ item.release }} not in pandoc_version_output.stdout )"{% endraw %}
