---
# install archive to /usr/local/bin
{% raw %}
- name: "check if binary already installed"
  command: "{{ item.dest }} --version"
  changed_when: false
  ignore_errors: true
  register: version_output

- name: install if binary not present
  block:
    - name: unpacking tools preset
      package:
        name:
          - tar
          - gzip
          - unzip
        state: present
      become: true

    - name: create temporary file
      tempfile:
        state: file
        suffix: temp
      register: tmp_archive

    - name: download archive
      get_url:
        url: "{{ item.url }}"
        dest: "{{ tmp_archive }}"
        checksum: "sha256:{{ item.sha256 }}"

    - name: unarchive
      unarchive:
        src: "{{ tmp_archive }}"
        dest: "{{ item.dir }}"
        extra_opts:
          - --strip=1
        remote_src: true
      become: true

    - name: delete temp file
      file:
        path: "{{ tmp_archive }}"
        state: absent
  when: "( version_output is failed ) or ( {{ item.release }} not in pandoc_version_output.stdout )"{% endraw %}
